In [1]:
import cv2
import numpy as np
import os
from scipy import ndimage

In [2]:
img=cv2.imread("lena5.jpg")

In [3]:
canny_img=cv2.Canny(img,200,300)

In [4]:
print(img)

[[[118 134 223]
  [118 134 223]
  [118 134 223]
  ...
  [131 148 215]
  [121 139 204]
  [113 131 196]]

 [[118 134 223]
  [118 134 223]
  [118 134 223]
  ...
  [133 150 217]
  [122 138 204]
  [113 131 196]]

 [[118 134 223]
  [118 134 223]
  [118 134 223]
  ...
  [133 149 216]
  [122 136 202]
  [111 127 193]]

 ...

 [[ 66  27  95]
  [ 66  27  95]
  [ 66  27  95]
  ...
  [104  77 157]
  [107  80 160]
  [109  82 162]]

 [[ 66  27  95]
  [ 66  27  95]
  [ 66  27  95]
  ...
  [107  80 160]
  [110  83 163]
  [112  85 165]]

 [[ 66  27  95]
  [ 66  27  95]
  [ 66  27  95]
  ...
  [109  82 162]
  [112  85 165]
  [114  87 167]]]


In [ ]:
cv2.imshow("Original Image",img)
cv2.imshow("3X3 image",canny_img)
cv2.waitKey(0)
cv2.destroyAllWindows()